from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Kalkulator")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.doClean = QtWidgets.QPushButton(self.centralwidget)
        self.doClean.setGeometry(QtCore.QRect(467, 220, 181, 51))
        self.doClean.setObjectName("pushButton")
        self.input_a = QtWidgets.QTextEdit(self.centralwidget)
        self.input_a.setGeometry(QtCore.QRect(220, 100, 191, 61))
        self.input_a.setObjectName("textEdit")
        self.input_b = QtWidgets.QTextEdit(self.centralwidget)
        self.input_b.setGeometry(QtCore.QRect(470, 100, 191, 61))
        self.input_b.setObjectName("textEdit_2")
        self.output = QtWidgets.QLineEdit(self.centralwidget)
        self.output.setGeometry(QtCore.QRect(220, 280, 441, 81))
        self.output.setObjectName("lineEdit")
        self.doCalc = QtWidgets.QPushButton(self.centralwidget)
        self.doCalc.setGeometry(QtCore.QRect(230, 220, 181, 51))
        self.doCalc.setObjectName("pushButton_2")
        self.check_dodaj = QtWidgets.QRadioButton(self.centralwidget)
        self.check_dodaj.setGeometry(QtCore.QRect(230, 180, 95, 20))
        self.check_dodaj.setObjectName("radioButton")
        self.check_odejmij = QtWidgets.QRadioButton(self.centralwidget)
        self.check_odejmij.setGeometry(QtCore.QRect(340, 180, 95, 20))
        self.check_odejmij.setObjectName("radioButton_2")
        self.check_mnoz = QtWidgets.QRadioButton(self.centralwidget)
        self.check_mnoz.setGeometry(QtCore.QRect(460, 180, 95, 20))
        self.check_mnoz.setObjectName("radioButton_3")
        self.check_dziel = QtWidgets.QRadioButton(self.centralwidget)
        self.check_dziel.setGeometry(QtCore.QRect(550, 180, 95, 20))
        self.check_dziel.setObjectName("radioButton_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("Kalkulator", "Kalkulator"))
        self.doClean.setText(_translate("Kalkulator", "Wyczyść"))
        self.doCalc.setText(_translate("Kalkulator", "Oblicz"))
        self.check_dodaj.setText(_translate("Kalkulator", "+"))
        self.check_odejmij.setText(_translate("Kalkulator", "-"))
        self.check_mnoz.setText(_translate("Kalkulator", "*"))
        self.check_dziel.setText(_translate("Kalkulator", "/"))
